//
//  TasksData.swift
//  Fiducia
//
//  Created by sap on 18/11/21.
//

import Foundation
import SwiftUI

class TasksData: ObservableObject {
    
    @Published var tasks = [Task(name: "Take public transport 🚆", difficulty: "1", steps: ["(If applicable) Open your browser and search for the train line map ", "Locate the destination you want to go to.", "Plan out your route. (no. of trains you need to change, etc)", "Head outside if you haven't done so", "(If applicable) Observe your surroundings for signs pointing to where your train is.", "Follow the signs and walk slowly so you don't miss any of them.", " While waiting, you can check the arrival time of your bus/train online through the train company's website.", "Be aware of the time.", "When the bus/train arrives, walk towards the door and stand at one side.", "(If applicable)Wait for all the people to exit. ", "Step into the bus/train.", "Move towards an open seat or an open area.", "Sit on the seat or stand at an open space.", "Take note of the stop/station you are alighting at.", "When you reach your destination, leave the bus/train.",]),
                            Task(name: "Thank a cleaner, bus driver, etc 🙏", difficulty: "1", steps: ["Find someone you want to thank.", "Write done what you want to thank them for e.g. 'Thanks for your hard work', 'Thank you for keeping the place clean', etc. You could also simply greet them 'Good morning'/'Good afternoon'/'Good evening'.", "Take a deep breath, steady your breathing.", "Walk a few steps towards them.", "As you walk, you can practice reciting what you want to say.", "Continue on at your own comfortable pace.",  "When you reach your target, breath in and out to calm down.", "Smile", "Greet them with a 'Good morning/afternoon/evening' + title : 'uncle/auntie'. ", "Apologise for disturbing their work.", "Say : 'I just wanted to tell you' then read out loud what you have recited", "Bow slightly.", "Leave"]),
                            Task(name: "Checking out by cashier when buying groceries 🛍️ ", difficulty: "1", steps: ["(Optional)Before you head out, bring a reusable bag to be more eco-friendly.", "Find the cashier with the shortest queue.", "Bring your items to the cashier and place them on the conveyer belt. \nTip💡 : Organise them by type. This will greatly help the cashier and yourself. Example, heavier canned food goes first, boxed items second, raw meat third, frozen, deli, diary items fourth, non food items fifth etc", "Let the cashier check out all your items. If you have brought your own bag, remember to tell the cashier.\nTip💡 : While waiting, find and take out your wallet to save time.", "Answer the cashier if you are a member or not with a simple yes or no, or head nod/ shake.", "Tell the cashier which payment method you're using e.g: 'Cash, please.' ", "Remove cash/credit card from wallet.", "Hand it to the cashier.", "Retrieve change/card when handed back.", "Receive your receipts and put them in the bag.", "Carry your bags.", "Double check from the recipt if the right amount has been deducted from your card and the right amount of change is given.", "Thank the cashier.\nTip💡 : If you do not wish to speak up, you can bow slightly.", "Take your items and leave."]),
                            Task(name: "Calming down (4-7-8 and 5-4-3-2-1 technique) 😮‍💨", difficulty: "1", steps: ["Focus on your breathing.", "Close your mouth and inhale through your nose for 4 seconds.", "Hold your mouth and count to 7.", "Exhale completely through your mouth, making a woosh sound, for 8 seconds.", "Repeat until your breath is steady.", "Now think of: 5 things you can see.", "4 things you can touch.", "3 things you can hear.", "2 things you can smell.", "1 thing you can taste.", "Open the 'notes' app.", "Type down every negative thought that comes into your mind. \nTip💡 : Don't try to stop your thoughts, embrace it instead. \nIt's okay to feel this way.", "Identify what type of thoughts they are : Jumping to conclusions? Catastrophizing? Overgeneralization? Labeling? 'Should' statements? Emotional reasoning? ", "Ask yourself if your thoughts are realistic.", "Type down realistic explanations or alternatives to the thoughts. \nExamples to challenge this thought : 'That man looking towards my direction is probably judging me because i look dumb not knowing where i am.' Think logically and write it down 'He might be looking for someone that's near me' or 'maybe he's looking off into blank space'.", "Realise that your thoughts are just thoughts and not reality.", "Repeat until you have completely gained a sense of yourself."]),
                            Task(name: "Greet a neighbour 👋", difficulty: "2", steps: ["Choose a neighbour, as well as a time when they are relaxed and not in a hurry.\nTip💡 : If you want, you can give them a gift, such as homemade treats or home grown veggies.", "Take a deep breath to slow down your heart.\nTip💡 : Try using the 4-7-8 technique!", "Walk a few steps towards your neighbour.", "Continue on slowly at your own pace until you have reached them.", "Greet them using : 'Hello', 'Good morning/ afternoon/ everning','How are you?', etc\nTip : If they don't seem to recognise you, you could tell them: 'I'm of your neighbours and I live near you.'", "(If applicable)Hand them the gift and tell them : 'I wanted to give this to you, there was too much of it so we had some leftovers. Hope you like it.' ", "Bow slightly.", "Thank them for their time.", "Turn to walk away."]),
                            Task(name: "Go out with a friend 👫", difficulty: "2", steps: ["Decide which friend you would like to make plans with. \nTip💡 : Make sure you are comfortable with that friend. If you would like to step out of your comfort zone, you could also choose a friend you are not close with.", "Plan your day with the notes app. \nEg. 2pm: eat lunch at a foodcourt, 3pm: watch a movie.", "Text your friend the time, date and place you would like to meet up.\nYou could start off by telling them: 'I'm bored, do you want to hang out tomorrow?', etc", "Beforehand, make sure you're relaxed and remeber the details of the meeting.", "Dress comfortably and arrive at the location 5 minutes before the appointed time.", "When you see your friend, take a deep breath and greet them.", "While you are walking, chat with your friend about some of the topics you have in common.", "Carry out the plan you and your friend have made.", "After the day has ended, take a deep breath and say goodbye to your friend.\nTip💡 : If you would like to leave but do not know how to, you could tell them: 'Sorry, I think my parents want me to come home by (a certain timing).", "Exit the scene by calmly walking away.\nTip💡 : Remember to say 'Goodbye'/'See you later'"]),
                            Task(name: "Calling a waiter over 🙋", difficulty: "2", steps: ["Recite what you want to say.", "Take a deep breath.", "Lift your hand off the table sllghtly." ,"Lift it a bit more", "Raise it slowly at your own pace.","Finally, take a deep breath and raise it all the way.", "While waiting, recite it again under your breath one last time.", "When the waiter comes, say recite what you want to say.\nTip💡 : If they don't notice you, you could call them by saying: 'Excuse me'", "(If applicable)When the waiter comes back, thank them by bowing slightly or saying thanks."]),
                            Task(name: "Start conversation with a new classmate/colleague 🗣", difficulty: "2", steps: ["Choose your unsuspecting classmate or colleague who seems free and relaxed.", "Take a deep breath, steady your breathing.", "Walk a few steps towards them.", "Continue on at your own comfortable pace.", "Smile and start with a simple 'Hi' or a wave of your hand.", "You can start a converastion by inquiring about their interests. Like saying, 'Hey, sorry for disturbing you, do you by any chance like (something)?'\nTip💡 : be observant, what themed objects do you see on their table, bag or phone? ", "If the topic of interest matches yours, go with the flow. \nIf it doesn't, ask more about it. \nStart with : 'I'm not really into (something) but it seems kinda interesting. Is (topic) easy to get into?' ", "In case you feel uncomfortable, you can always exit the conversation by saying : 'Sorry i have to go to the toilet, thanks for your time. I enjoyed talking.'"]),
                            Task(name: "Introduce yourself 🤝", difficulty: "2", steps: ["Think of what you want to say.\nTip 💡: Include your name, hobbies or anything that you want others to know about you. It can be your favourite food, favourite shows, etc..", "Write down what you want to say in the the notes app.", "Recite your script in your head.","Take a deep breath.", "Stand up when it is your turn to introduce yourself.", "Make eye contact with the audience.\nTip💡 : You don't actually have to make eye contact. Look in between the eyes, or on the forehead.", "Speak loudly so you can be heard.\nTip: Use your diaphragm. Inhale and exhale deeply, and try to feel your voice coming from the bottom of your lungs.", "When you're done, smile and thank the audience by either thanking out loud or bowing.", "Sit back down."]),
                            Task(name: "Order food/drink from hawker centre/restaurant 🧋", difficulty: "2", steps: ["(If applicable)Locate the stall you want to order from and where the queue is.", "Stand up from seat.", "Take a deep breath and walk a few steps forwards.", "Continue on at your own pace.", "Once you reach the stall, find the meal you want to order.\nTip💡 : If you're too afraid to approach in fear the stall owner might suddenly call upon you, you can use your phone to take a picture of the menu and then enlargen it.", "Open the 'notes' app.","Jot down what you want to order.", "Take a deep breath to calm down.\nTip💡 : Try the 4-7-8 breathing technique.", "Walk up to the stall and wait for your turn (if there's a queue).", "While waiting, recite your order in your mind. You can also try to find an empty space for you to stand later.", "When it's your turn, read out your order.\nTip💡 : Reading fast might make you stumble over your words. Read slowly and steadily. It's okay, no one will judge you.", "After you're done, walk to an empty space while your order is being prepared.\nTip💡 : good job :) you're almost there.", "Take note of where your table is + how your order looks.", "When you see it's done or you're called up, take the order (and cutlery if not given) and thank them.\nTip💡 : If you do not want to speak, you can bow slightly or nod your head.", "Slowly walk back to your table."]),
                            Task(name: "Eat in front of others 🍱", difficulty: "3", steps: ["Prepare some napkins at one side.", "Hold the cutlery in one hand.", "Re-enforce yourself with some positive self talk.","Do not start until your hands stop shaking", "Take a deep breath.", "Slowly lift your cutlery and pick up a small amount of food.", "Guide the cutlery into your mouth.", "Chew thoroughly. \nTip💡 : Chew around 15 times for small bites and 30 times for bigger bites.", "Repeat the steps until the food is all gone. \nTip💡 : If you're bold enough, try purposely eating messy, studies show that this will help build your confidence by showing you that it's not a big deal as your brain makes it out to be \nTip 2.0💡 : If you spill the food, don't worry, just remember you have napkins on hand and use it. If you're in a resturant, you can call on a waiter to help.", "(If you're in a resturant:) When you finish your meal, pay for the meal.\nTip💡 : As you head out, you can thank the staff by bowing slightly or nodding your head."]),
                            Task(name: "Make a call 📱", difficulty: "2", steps: ["Write down what you want to say on a piece of paper.", "Open the phone app.", "Type in the first digit of the phone number.", "Type in the rest of the digits at your own pace.", "Focus on the goal of the phone call.", "Open the notes app.", "List down what can go wrong, do not overthink this part.", "Write down ways to combat this.", "Return to the phone app.", "Hover your finger over the call button.", "Take a deep breath.", "Lower your finger.", "Take another breath, hold it, close your eyes and press the button.", "Place the phone to your ear, or press the speakerphone button.", "When the call is picked up, introduce yourself.", "Read out your script.", "Answer any questions asked slowly.", "Thank them before they, or you hang up."]),
                            Task(name: "Do a presentation 📋", difficulty: "3", steps: ["Prepare a script to help you remember what you need to say.\nTip💡 : Make sure the words and lines are spread apart so that you can read the words easily. You could also make your script into a bullet point list if it helps you remember which parts are more important.", "If there is a Q&A session after the presentation, you can brainstorm possible questions and answers.", "Practice presenting by yourself or in front of your family members.\nTip💡 : If you are presenting with a group, take note of who is presenting before you and when you should start talking.", "While waiting for your turn, visualise your presentation going smoothly.", "Tip💡 : You can pretend your nervousness is excitement.", "Take one step forward.", "Take another few step forwards.", "Slowly walk to the stage at your own pace.", "When you present, try to make eye contact with your audience. \nTip💡 : Just look in between their eyes, don't have to make actual contact unless you're comfortable. Make sure to look around, and not to focus on only one person in the auidence.", "Take a deep breath.", "Slowly and calmly recite your script, nobody is going to rush you. Try to read loudly and clearly.\nTip💡 : Don't keep looking at your script, switch between reading your script and looking at your audience. Look for friendly faces in the audience, like your friends.", "When you are done, you can bow slightly or nod your head.", "Slowly exit the stage, calm your breathing." ]),
                            Task(name: "Making friends at an event 👥", difficulty: "3", steps: ["Beforehand, make sure you're relaxed and ready for the event ", "Decide on an arrival time. \nTip💡 : It's always good to be early.", "By writing down a list, check if you have brought eveything you need or want.", "While travelling to the location, think of some topics for discussion.\nTip💡 : People like questions about themselves. You can also talk about current events like upcoming movies etc", "Once you arrive, locate the venue.\nTip : If you are unsure, you can ask a mutual attending the event/any organising staff for directions.", "Take your time to walk there.", "Calm yourself down before entering.\nTip💡 : Drink some water, engage in some positive self talk. ", "Enter the venue.", "Locate friends or people who are familiar faces.\n If there is none, find an empty area to rest at.", "Look for a friendly face in the crowd, especially one who is alone as well.", "Think of how to talk to them. \nTip💡 : Comment on the surroundings, for example : 'The food looks good' or 'This event seems fun'.", "Imagine positive scenarios with this person to encourage yourself. ", "Find the easiest path to approach this person.", "Take a few steps forward.", "Continue on at your own pace.\nTip💡 : Make sure your body is relaxed and casual. You could listen to some of your favourite music to calm yourself down.", "Unclench your hands and relax your shoulders.", "Take a deep breath.", "Say what you have planned out loud.\nTip💡 : If the person doesn't reciprocate, tell them: 'Sorry for disturbing', bow slightly and leave. Don't feel too discouraged, they might not feel comfortable talking to a stranger too. You can approach someone else who seems more outgoing.", "Go with the flow, continue the conversation.\nTip💡 : You can ask questions like 'By the way, what's your name?' or compliments like 'I came to say I like your outfit, I think it's very nice. Where did you buy it?'.", "Remember to smile but do not force it.", "If the event is too loud/crowded and overwhelming for you, you can excuse yourself before it gets worse.\nTip💡 : You can leave a conversation by saying: 'Sorry, I have to go to the bathroom, I'll be back soon.' ", "Identify a place where you can be alone and decompress, like the bathroom, or a hidden corner.", "Take as much time as you need to recover.\nTip 💡: Ground yourself. Try the 5-4-3-2-1 technique—Find 5 things you can see, 4 things you can touch, 3 things you can hear, 2 things you can smell and 1 thing you can feel.", "Once you have calmed down, you can slowly return. If it's still too much, it's best to return home.\nTip💡 : You can excuse yourself by saying: 'Sorry, something suddenly came up and I have to leave.' "])]
                            
                            
                            
                            
                            
                            
    func getArchiveURL() -> URL {
        let plistName = "tasks.plist"
        let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        
        return documentsDirectory.appendingPathComponent(plistName)
    }
    
    func save() {
        let archiveURL = getArchiveURL()
        let propertyListEncoder = PropertyListEncoder()
        let encodedTasks = try? propertyListEncoder.encode(tasks)
        try? encodedTasks?.write(to: archiveURL, options: .noFileProtection)
    }
    
    func load() {
        let archiveURL = getArchiveURL()
        let propertyListDecoder = PropertyListDecoder()
        
        var finalTasks: [Task]!
        
        if let retrievedTasksData = try? Data(contentsOf: archiveURL),
           let decodedTasks = try? propertyListDecoder.decode(Array<Task>.self, from: retrievedTasksData) {
            finalTasks = decodedTasks
        } else {
            finalTasks = tasks
        }
        
        tasks = finalTasks
    }
}
